import { Injectable, Logger } from '@nestjs/common';
import PDFDocument from 'pdfkit';
import archiver from 'archiver';
import { PassThrough } from 'stream';

export interface ContentItem {
  title: string;
  content: string;
}

@Injectable()
export class ProductBuilderService {
  private readonly logger = new Logger(ProductBuilderService.name);

  async generatePDF(title: string, items: ContentItem[]): Promise<Buffer> {
    return new Promise((resolve, reject) => {
      const doc = new PDFDocument({ margin: 50 });
      const buffers: Buffer[] = [];

      doc.on('data', buffers.push.bind(buffers));
      doc.on('end', () => {
        const pdfData = Buffer.concat(buffers);
        resolve(pdfData);
      });
      doc.on('error', reject);

      // Cover Page
      doc.fontSize(24).fillColor('black').text(title, { align: 'center' });
      doc.moveDown(2);
      doc.fontSize(14).fillColor('grey').text('Generated by AI Content Factory', { align: 'center' });
      doc.addPage();

      // Content Items
      items.forEach((item, index) => {
        doc.fontSize(16).fillColor('black').text(`${index + 1}. ${item.title}`);
        doc.moveDown(0.5);
        doc.fontSize(12).fillColor('#333333').text(item.content);
        doc.moveDown(2);

        // Add a page break every 5 items to keep it clean, except for the last item
        if ((index + 1) % 5 === 0 && index !== items.length - 1) {
          doc.addPage();
        }
      });

      doc.end();
    });
  }

  async createZipPack(pdfBuffer: Buffer, zipFilename: string): Promise<Buffer> {
    return new Promise((resolve, reject) => {
      const buffers: Buffer[] = [];
      const passThrough = new PassThrough();

      passThrough.on('data', buffers.push.bind(buffers));
      passThrough.on('end', () => resolve(Buffer.concat(buffers)));
      passThrough.on('error', reject);

      const archive = archiver('zip', { zlib: { level: 9 } });
      archive.on('error', reject);
      archive.pipe(passThrough);

      archive.append(pdfBuffer, { name: `${zipFilename}.pdf` });
      archive.append('Licensing Terms: You may use this content commercially. Do not resell the raw files.', { name: 'README-LICENSE.txt' });

      archive.finalize();
    });
  }
}
